name: Godot Universal Serializer 2 Upload
description: Upload Godot Cpp and the Godot Universal Serializer 2 Extension.

runs:
  using: composite
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Godot Universal Serializer 2
        path: |
          ${{ github.workspace }}/dist/addons/com.daylily_zeleen.godot_universal_serializer2/bin/libgus2.${{ inputs.artifact_file_suffix }}
        retention-days: 14
