name: Godot Universal Serializer 2 Upload
description: Upload Godot Cpp and the Godot Universal Serializer 2 Extension.

runs:
  using: composite
  steps:
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Godot Universal Serializer 2
        path: |
          ${{ github.workspace }}/demo/**
        retention-days: 14
