name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  SCONSFLAGS: verbose=yes warnings=extra werror=yes

jobs:
  ios:
    runs-on: "macos-latest"
    name: iOS Build xcframework
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - name: Setup python and scons
        uses: ./.github/actions/deps

      - name: Build iOS xcframework
        shell: sh
        run: |
          bash misc/build_ios.sh

      - name: Upload iOS xcframework
        uses: ./.github/actions/upload
        with:
          platform: ios
          artifact_file_suffix: ios.xcframework/
          artifact_name: GUS2-ios
