name: 🐧 Linux Builds
on:
  workflow_call:

# Global Settings
env:
  SCONSFLAGS: verbose=yes warnings=extra werror=yes

jobs:
  linux:
    runs-on: ubuntu-20.04
    name: Linux Build ${{ matrix.target }} ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        arch: [x86_64]
        shlibsuffix: [so]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build ${{ matrix.target }} ${{ matrix.arch }}
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          arch: ${{ matrix.arch }}
          platform: linux
          target: ${{ matrix.target }}

      - name: Upload ${{ matrix.target }} ${{ matrix.arch }}
        uses: ./.github/actions/upload
        with:
          platform: linux
          artifact_file_suffix: linux.${{ matrix.target }}.${{ matrix.arch }}.${{ matrix.shlibsuffix }}

